/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 自分情報取得API
         * @description **自分情報取得API**<br/>
         *     <br/>
         *     <br/>
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["GetMe"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * サインアップAPI
         * @description **サインアップAPI**</br>
         *     <br/>
         *     <br/>
         *     - Eメールアドレス
         *     - ユーザー名
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignUp"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unexpected error. */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/normal/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログインAPI
         * @description **Emailアドレスを使用して、CognitoにサインインするためのAPI**</br>
         *     <br/>
         *     <br/>
         *     本システムは、LINEログインを行うことが可能。<br/>
         *     LINEログインを使用しないユーザー向けの認証API
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["SignIn"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unexpected error. */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * LINE認証リダイレクトAPI
         * @description **LINE認証を行うためのURLにリダイレクトさせるAPI**</br>
         *     <br/>
         *     LINEログインを行うためには、以下のURLにクライアントを誘導させる必要がある。</br>
         *     その際、`https://access.line.me/oauth2/v2.1/authorize`にリダイレクトさせる必要があるが、</br>
         *     他にもLINEのClientID等が必要になる。</br>
         *     これらをフロントエンド側に持たせるのでなく、バックエンド側でラップすることで情報を集約させる目的で本APIでラップするもの。</br>
         *     </br>
         *     </br>
         *     **FYI. [Go言語]LINE ログイン連携方法**
         *     - https://qiita.com/KWS_0901/items/8c4accdda43bc9f26a57
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description リダイレクトURLを返す */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/line/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * LINEコールバックAPI
         * @description **LINE認証コールバックAPI**<br/>
         *     LINE認可エンドポイントにアクセスし、ログイン情報を入力後、認可コードを受けるためのコールバックAPIである。<br/>
         *     認可コードと、LINEクライアントシークレットを用いてOAuth2認証を行い、AccessTokenを取得する。
         *     AccessTokenをCookieにセットし、ログイン後の画面に
         *     Cognitoから送られてくるアクセストークンをCookieにセットし、ログイン後の画面にリダイレクトを行う
         *     </br>
         *     </br>
         *     **FYI. [Go言語]LINE ログイン連携方法**
         *     - https://qiita.com/KWS_0901/items/8c4accdda43bc9f26a57
         *
         */
        get: {
            parameters: {
                query: {
                    code: string;
                    state: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description アクセストークン
                 *      */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unexpected error. */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * カテゴリ一覧API
         * @description カテゴリをデフォルトで全件取得して返却します <br>
         *     idの昇順。
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["GetCategories"];
            };
        };
        put?: never;
        /**
         * カテゴリ登録API
         * @description カテゴリを登録します!
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories/{categoryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * カテゴリ更新API
         * @description カテゴリを更新します
         *
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * カテゴリ削除API
         * @description カテゴリを削除します
         *
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    categoryId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TODO取得API
         * @description TODO一覧を取得して返却します<br/>
         *
         */
        get: {
            parameters: {
                query?: {
                    offset?: number;
                    limit?: number;
                    status?: "DONE" | "TODO";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["GetTodoList"];
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * TODO登録API
         * @description TODOを登録します<br/>
         *     デフォルトで、`done(タスク状態)`をfalseにします
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        categoryId?: number;
                        /** Format: date */
                        dueDate?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/todo/{todoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * TODO詳細API
         * @description TODOを１つ取得します
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    todoId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["GetTodo"];
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unexpected error. */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /**
         * TODO更新API
         * @description TODOの情報を更新します<br/>
         *     更新できる情報として以下があります<br/>
         *     - カテゴリ
         *     - TODOの名称
         *     - 期限
         *
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    todoId: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name?: string;
                        categoryId?: number;
                        /** Format: date */
                        dueDate?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        /**
         * TODO論理削除API
         * @description TODOを論理削除（doneの値を切り替える）します
         *
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    todoId: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unexpected error. */
                "5XX": {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping/item/{owner_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 買い物リスト取得API
         * @description `owner_id`で指定した買い物リストを取得します<br/>
         *     <br/>
         *     買い物アイテムのIDの昇順で返され、`picked` = `true`になっているレコードについては、<br/>
         *     返却対象外
         *
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description オーナーID(所属している家庭単位のID) */
                    owner_id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                200: components["responses"]["GetShoppingItemList"];
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        /**
         * 買い物登録API
         * @description 買い物メモを登録します<br/>
         *
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description オーナーID(所属している家庭単位のID) */
                    owner_id: number;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /**
                         * @description food または、 necessity
                         *
                         * @example food
                         */
                        category?: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            id?: number;
                            /** @enum {string} */
                            category?: "food" | "necessity";
                            description?: string;
                        };
                    };
                };
                /** @description Authorization information is missing or invalid. */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Me: {
            id?: number;
            user_name?: string;
            /** Format: email */
            email?: string;
            /** @enum {string} */
            authority?: "COMMON" | "ADMIN";
        };
        SignUp: {
            email?: string;
            password?: string;
            username?: string;
        };
        SignIn: {
            email?: string;
            password?: string;
        };
        Category: {
            id?: number;
            name?: string;
        };
        Todo: {
            id?: number;
            name?: string;
            category?: components["schemas"]["Category"];
            /**
             * Format: date
             * @example 1990-01-01
             */
            dueDate?: string;
            done?: boolean;
        };
        GetShoppingItem: {
            id: number;
            owner_id: number;
            name: string;
            /** @example food */
            category: string;
            picked: boolean;
        };
        UserBase: {
            id: string;
            name: string;
            address: string;
            /**
             * Format: date
             * @example 1909-01-01
             */
            birthday: string | null;
            age: number | null;
            /** @enum {string} */
            sex: "MALE" | "FEMALE";
            memberType: components["schemas"]["MemberType"];
        };
        User: components["schemas"]["UserBase"] & {
            /** @example 09012345678 */
            phoneNumber: string;
            /** @example sample@example.com */
            email: string | null;
        };
        /** @enum {string|null} */
        MemberType: "GENERAL" | "SPECIAL" | "CHILD" | "SENIOR" | null;
        /** @enum {string} */
        Trigger: "HP" | "INTRODUCTION" | "TVCM" | "HOTPEPPER" | "FLYER" | "NONE";
        GeneralError: {
            /**
             * Format: int
             * @example エラーカテゴリ/エラータイプ
             */
            code?: string;
        };
    };
    responses: {
        /** @description successful operation */
        GetMe: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Me"];
            };
        };
        /** @description successful operation */
        GetTodoList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Todo"][];
            };
        };
        /** @description successful operation */
        GetShoppingItemList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GetShoppingItem"][];
            };
        };
        /** @description successful operation */
        GetShoppingItem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GetShoppingItem"];
            };
        };
        /** @description successful operation */
        GetTodo: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Todo"];
            };
        };
        /** @description successful operation */
        GetCategories: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Category"][];
            };
        };
        /** @description successful operation */
        GetUsers: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["UserBase"][];
            };
        };
        /** @description Successful operation */
        GetUser: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Not found. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GeneralError"];
            };
        };
        /** @description Illegal input for operation. */
        IllegalInput: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GeneralError"];
            };
        };
        /** @description Internal Server Error */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GeneralError"];
            };
        };
    };
    parameters: {
        /** @description ユーザーID */
        UserId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
